In [1]:
import tensorflow as tf 

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.13365297, -0.61727136,  0.32868537, -0.57862407, -0.24205935,
         0.5457508 ,  0.06844109,  0.36083764, -0.03966779, -0.17647645]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.10940035, 0.05162932, 0.13295975, 0.05366371, 0.07513615,
        0.16519257, 0.10249379, 0.13730417, 0.09199124, 0.08022898]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.8006433

In [11]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4872 - accuracy: 0.8595
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1521 - accuracy: 0.9546
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1055 - accuracy: 0.9690
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0880 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0760 - accuracy: 0.9763


In [13]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0720 - accuracy: 0.9792


[0.07202880084514618, 0.979200005531311]

In [14]:
predictions1 = model(x_train[:1]).numpy()
predictions1

array([[ -8.932205 ,  -6.6407948,  -5.4379783,   7.39318  , -24.829046 ,
         12.713011 , -15.522408 ,  -6.173183 , -10.832906 ,  -5.977751 ]],
      dtype=float32)

In [16]:
loss_fn(y_train[:1], predictions1).numpy()

0.004881607

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1643496e-05, 3.2417431e-09, 1.2229714e-05, 8.7620318e-04,
        3.4339742e-10, 7.3433766e-06, 7.6475366e-13, 9.9908364e-01,
        2.1246890e-06, 6.7496912e-06],
       [3.7427067e-10, 2.4825986e-04, 9.9973816e-01, 1.1707717e-05,
        1.6374914e-15, 1.6698561e-06, 7.9657343e-11, 1.7159406e-13,
        2.5002439e-07, 4.1563561e-14],
       [1.6778886e-08, 9.9831367e-01, 2.0312467e-04, 9.7178090e-06,
        1.2907087e-05, 1.0378477e-05, 4.5351044e-05, 1.0791651e-03,
        3.2545527e-04, 2.9004548e-07],
       [9.9960107e-01, 3.0461982e-09, 1.0145410e-04, 1.4625030e-06,
        2.2495353e-08, 1.7190853e-06, 7.2967082e-06, 1.8971354e-04,
        1.3214472e-07, 9.7111188e-05],
       [1.9735214e-06, 5.0207518e-07, 3.3761975e-05, 1.3692860e-06,
        9.9270779e-01, 7.1995011e-08, 2.2413444e-06, 2.3624025e-05,
        1.6461452e-06, 7.2270697e-03]], dtype=float32)>

In [19]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)